data(airquality)
Temp=airquality$Temp
TempK=(Temp-32)*5/9 + 273.15
pdf("Apartado1.pdf", width=10, height=7)
par(mfrow=c(4,1))
plot(1:length(airquality$Day), airquality$Ozone, xlab="Dias", ylab="Ozono", main="Ozono respecto a días")
plot(1:length(airquality$Day), airquality$Solar.R, xlab="Dias", ylab="Irradiancia solar", main="Irradiancia respecto a días")
plot(1:length(airquality$Day), airquality$Wind, xlab="ento", main="Viento respecto a Dias", ylab="Velocidad del viento")
plot(1:length(airquality$Day), TempK, xlab="Días", ylab="Temperatura", main="Temperatura respecto a días")
dev.off()
pdf("Apartado2.pdf")
par(mfrow=c(2,2))
hist(airquality$Ozone, xlab="Concentración de ozono (ppb)", ylab="Frecuencia", main="Histograma de la concentración de ozono")
hist(airquality$Solar.R, xlab="Irradiancia (Langleys)", ylab="Frecuencia", main="Histograma de la irradiancia")
hist(airquality$Wind, xlab="Velocidad del viento (millas/hora)", ylab="Frecuencia", main="Histograma de la velocidad del viento")
hist(TempK, xlab="Temperatura (Kelvin)", ylab="Frecuencia",  main="Histograma de la temperatura")
dev.off()
Ozono=airquality$Ozone
print("Apartado 3, cálculo de variables estadísticas del ozono")
print("Cálculo de la media aritmética, el valor medio del ozono si quitar los NA no se puede calcular, sin embargo quitando los valores NA de la columna queda")
print("Primero quitamos los valores NA de la columna Ozono")
OzonosinNA=na.omit(Ozono)
mean(OzonosinNA)
print("apartado a, cálculo de la media artimética")
OzonosinNAmedia=mean(OzonosinNA)
print(OzonosinNAmedia)
print("apartado b, la media geométrica es")
OzonoGeometrica=prod(OzonosinNA)^(1/length(OzonosinNA))
print(OzonoGeometrica)
print("apartado c, la media armónica es")
OzonoArmonica=1/mean(1/OzonosinNA)
print(OzonoArmonica)
print("apartado d, la media cuadrática")
OzonoCuadratica=sqrt(sum(OzonosinNA^2)/length(OzonosinNA))
print(OzonoCuadratica)
print("Apartado e, la mediana")
print(median(OzonosinNA))
print("apartado 4, Cálculo de variables estadísticas para la temperatura")
print("primero, quitamos los valores nulos de la temperatura")
print("Como la variable Temp no tiene valores NA, no tiene sentido quitarlos, así que vamos a calcular lo pedido")
a=mean(TempK)
print(mean(TempK))
print("a) Cálculo de la desviación típica")
print(sd(TempK))
print("Apartado b, rango semiintercuartílico")
print(IQR(TempK)/2)
print("Apartado c, la desviación absoluta mediana MAD")
print(sum((abs(TempK-median(TempK))))/length(TempK))
MAD=mad(TempK, constant=1)
MADabs=1.4826*MAD
print(MADabs)
print("La medida menos robusta en este apartado es la desviación típica")
print("Apartado 5")
print("Primero, para hallar los coeficientes de variación de cada variable, es necesario quitar los valores NA de cada de las variales")
print("Hallemos las medidas de dispersión para el ozono")
PearsonOzono=(sd(OzonosinNA)/abs(mean(OzonosinNA)))
print(PearsonOzono)
print("Luego para el Coeficiente de irradiación solar")
SolarsinNA=na.omit(airquality$Solar.R)
PearsonSOlar=(sd(SolarsinNA)/abs(mean(SolarsinNA)))
print(PearsonSOlar)
print("Ahora la velocidad del viento")
WindsinNA=na.omit(airquality$Wind)
PearsonWind=sd(WindsinNA)/abs(mean(WindsinNA))
print(PearsonWind)
print("Y por íultimo la temperatura, que ya está calculada del apartado anterior")
PearsonTemp=sd(TempK)/abs((mean(TempK)))
print(PearsonTemp)
print("de las medidas tomadas con el coeficiente de Pearson, se ve que la medida que menos varía es la Temperatura")
print("Apartado 6a: Cálculo de la asimetría de Fisher")
skew=function(x){
  m3=sum((x-mean(x))^3)/length(x)
  s3= sd(x)^3
  m3/s3
}
print("Asimetría de Fisher del Ozono")
print(skew(OzonosinNA))
print("Asimetría de Fisher del coeficiente solar")
print(skew(SolarsinNA))
print("Asimetría de la Temperatura")
print(skew(TempK))
print("Asimetría de la velocidad del viento")
print(skew(WindsinNA))
print("Apartado 6b: Calculo de la asimetría de curtosis")
kurtosis=function(x){
  m4=sum((x-mean(x))^4)/length(x)
  s4=var(x)^2
  m4/s4
}
print("Asimetria de curtosis del ozono")
print(kurtosis(OzonosinNA))
print("Asimetría de curtosis del coeficiente solar")
print(kurtosis(SolarsinNA))
print("Asimetría de curtosis de la velocidad del viento")
print(kurtosis(WindsinNA))
print("ASimetria de curtosis de la temperatura")
print(kurtosis(TempK))
pdf("Apartado7.pdf")
plot(ecdf(SolarsinNA), verticals=TRUE, do.points=FALSE, lwd=2, xlab="Valores de la radiación solar (Langleys)", ylab="Frecuencias relativas acumuladas", main="Función de distribución acumulada empírica", cex.lab=1.3)
abline(h=0.5, lty=2)
print(median(SolarsinNA))
dev.off()
pdf("Apartado8.pdf")

#pairs(TempK, SolarsinNA)
#pairs(OzonosinNA, SolarsinNA)
#pairs(WindsinNA, SolarsinNA)
#pairs(SolarsinNA, airquality$Day)
#Concentración de Ozono frente la irradiación solar
airquality$Temp=TempK
pairs(airquality[,1:4], sch=19)
dev.off()