data(airquality)
viento=airquality$Wind
cat("Problema 1",'\n')
cat("Apartado a), '\n")
cat("Comprobemos si cumple el valor significativo a 9.3 mph", '\n')
z = (mean(viento) - 9.3)/(sd(viento/sqrt(length(viento))))
alpha=0.05
zalpha= qt(1-alpha/2, df=length(viento)-1)
cat("El valor de z es:", z, '\n')
cat("Mientras que el valor de z.alpha/2 es:", zalpha, '\n')
cat("Comprobamos si es significativamente diferente con z < z.alpha", '\n')
cat(z < zalpha, '\n')
cat("entonces vemos que se trata de un valor significativamente diferente a 9.3 mph", '\n')
cat("Apartado b)",'\n')
cat("Nivel de significacion mínimo", '\n')
tr=t.test(viento, mu=9.3, conf.level=0.95)
print(tr$p.value)
cat("Apartado c)", '\n')
z1=(mean(viento)-9.5)/sqrt(sd(viento)/length(viento))
talpha=qnorm(1-alpha)
cat("Haciéndolo de manera análoga que el apartado a), pero esta vez con un contraste unilateral, vemos que el valor de z vale:", z1, '\n')
cat("Mientras que el valor de z.alpha es de:", '\n')
cat("Realizando la comparación", '\n')
cat (z1 > talpha, '\n')
cat("Como vemos, se acepta la hipótesis nula y no es significativamente mayor", '\n')
cat("Apartado d)", '\n')
cat("Obtenemos el valor de significacion minimo", '\n')
min=t.test(viento, alternative="greater", mu=9.5, conf.level=0.95)
print(min$p.value)
cat("vemos como no se rechaza la hipótesis nula", '\n')
cat("Problema 2", '\n')
cat("Apartado a)", '\n')
cat("Comprobamos si la desviación típica de la población igual a un valor de 3mph", '\n')
estad=(length(viento)-1)*var(viento)/(3^2)
inter1=qchisq(alpha/2, df=length(viento)-1)
inter2=qchisq(alpha/2, df=length(viento)-1, lower.tail=F)
print(estad > inter1 & estad < inter2)
cat("Como vemos, está fuera del intervalo, así que lo rechazamos, no puede ser igual a 3 mph", '\n')
cat("Apartado b)", '\n')
cat("Comprobamos el nivel de significacion minimo", '\n')
#Importamos la libreria EnvStats
library("EnvStats")
tr=varTest(viento, conf.level=0.95, alternative = "two.sided",sigma.squared=3^2)
cat(tr$p.value, '\n')
cat("Ejercicio 3", '\n')
cat("La tabla de valores pedida queda como:", '\n')
tabla=tapply((airquality$Temp- 32)*5/9 + 273.15, airquality$Month, mean)
print(tabla)
cat("Ejercicio 4, '\n")
cat("Comprobar el gráfico adjunto", '\n')
data("airquality")
Temperatura=(airquality$Temp[!is.na(airquality$Temp)]-32)/1.8+273.15
meses=airquality$Month
Tablabuena=data.frame(Temperatura,meses)
pdf("Grupo1_Barajas_Martin_Marcial_Cuestion4.pdf")
t=boxplot(Tablabuena$Temperatura~Tablabuena$meses,vertical=TRUE, border = c("red", "yellow", "green","violet","dark blue"),ylab="Temperatura(K)",xlab="Meses del año",main="Diagrama de las distribuciones de temperatura")
dev.off()
t=boxplot(Tablabuena$Temperatura~Tablabuena$meses,vertical=TRUE, border = c("red", "yellow", "green","violet","dark blue"),ylab="Temperatura(K)",xlab="Meses del año",main="Diagrama de las distribuciones de temperatura")
#Repito el comando para que aparezca tanto en pdf como en la caja de gráficas de R
cat("Ejercicio 5", '\n')
junio=subset(Temperatura, airquality$Month==6)
julio=subset(Temperatura, airquality$Month==7)
agosto=subset(Temperatura, airquality$Month==8)
a=t.test(julio,junio, alternative="greater", conf.level=0.95)
b=t.test(julio,agosto, alternative="two.sided", conf.level=0.95)
cat("el valor de p para julio respecto a la media del mes de junio es:", a$p.value, '\n')
cat("el valor de p para agosto respecto a la media del mes de julio es:", b$p.value, '\n')
cat("Con estos valores, vemos que para el primero no es significativamente diferente, mientras que para Agosto si lo es")